CREATE VIEW [dbo].[ODT_OUTPUT_DETAIL_VW]
AS 
SELECT A.*,
    OPL.opl_description AS OPUS_NAME,
    (select aao.kna_id_activity from aao_available_activity_outcome_tb aao where aao.out_id_outcome = A.out_id) as KNA_ID
FROM 
(SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    O.START_DATE, O.END_DATE, O.TOTAL_DURATION
FROM ODT_GENERAL_EVENT_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    O.START_DATE, O.END_DATE, O.TOTAL_DURATION
FROM ODT_LANGUAGE_GROUP_EVENT_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    O.START_DATE, O.END_DATE, O.TOTAL_DURATION
FROM ODT_MOODLE_EVENT_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    O.START_DATE, O.END_DATE, O.TOTAL_DURATION
FROM ODT_EXTERNAL_EVENT_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    O.START_DATE, O.END_DATE, O.TOTAL_DURATION
FROM ODT_GENERAL_SERVICE_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    O.START_DATE, O.END_DATE, O.TOTAL_DURATION
FROM ODT_MOODLE_SERVICE_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    O.START_DATE, O.END_DATE, O.TOTAL_DURATION
FROM ODT_LANGUAGE_SERVICE_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    O.START_DATE, O.END_DATE, O.TOTAL_DURATION
FROM ODT_COLLABORATIVE_LEARNING_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    NULL, NULL, 0
FROM ODT_KNOWLEDGE_PRODUCT_DETAIL_VW O
--WHERE O.DELETED_DATE IS NULL
UNION ALL
SELECT O.OUT_ID, O.NAME, O.OBJECTIVES, O.COMMENTS, O.MODALITY, O.PRESENTATION_TYPE, O.SUBJECT_TYPE, O.OPUS_CODE,
    O.OUT_TYPE, O.LOCATION_NAME, O.LOCATION_TYPE, O.LOCATION_CITY,
    NULL, NULL, 0
FROM ODT_FHL_PRODUCT_DETAIL_VW O
/*WHERE O.DELETED_DATE IS NULL*/) AS A,
    Ops_Opus_tb OPS,
    Opl_Opus_Language_tb OPL
WHERE OPS.ops_id = OPL.ops_id
    AND OPL.lng_id = 1
    AND OPS.ops_activity_code = A.OPUS_CODE